name:  Sowar
author:  Dirar Abu Kteish (dirar@zanstudio.com)
current:  1.00
category:  Widgets
tags:  [image, carousel, animation, slideshow, left, right]
demo:  http://www.developer.ps/moo/Sowar
docs:  http://www.developer.ps/moo/Sowar