name:  Sowar
author:  dirar
current:  1
category:  Widgets
sources: ["Source/Sowar.js"]
tags:  [image,carousel,animation,slideshow]
demo:  http://www.developer.ps/moo/Sowar
docs:  http://www.developer.ps/moo/Sowar